### ISSUE TITLE
FITS opacity no longer honored

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/wwt-webgl-engine#106]
At least, I think that's the case. In the pywwt-notebooks demos, opacity adjustments for FITS images used to work fine, but now the image is 100% opaque no matter what I set the opacity to.

@imbasimba would you be able to look into this?

**Comment by imbasimba** [comment]
I'll look into it right away

**Comment by imbasimba** [comment]
https://github.com/WorldWideTelescope/wwt-webgl-engine/pull/108

**Comment by pkgw** [comment]
Thanks! Glad to see that it's such a straightforward fix.
