### ISSUE TITLE
Non-FITS SkyImages broken

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/wwt-webgl-engine#113]
Hey @imbasimba, it seems that your FITS/WebGL work has broken "SkyImage" imagesets — these are JPG-type images that are *not* tiled for display. For instance, this URL should show an image:

http://worldwidetelescope.org/webclient/?wtml=http%3A%2F%2Fwwtcoreapp-data-app.azurewebsites.net%3A80%2Fwwtweb%2FShowImage.aspx%3Freverseparity%3DFalse%26scale%3D19.976349%26name%3D60mmorion5hrflabgdnpsr.TIF.jpg%26imageurl%3Dhttps%3A%2F%2Fnova.astrometry.net%2Fimage%2F11018065%26credits%3DAstrometry.net%2BUser%2B(All%2BRights%2BReserved)%26creditsUrl%3D%26ra%3D87.272483%26dec%3D-9.748588%26x%3D580.4%26y%3D2233.9%26rotation%3D-93.05%26thumb%3Dhttps%3A%2F%2Fnova.astrometry.net%2Fimage%2F11018069%26wtml%3Dtrue

(The underlying WTML URL is:

http://wwtcoreapp-data-app.azurewebsites.net/wwtweb/ShowImage.aspx?reverseparity=False&scale=19.976349&name=60mmorion5hrflabgdnpsr.TIF.jpg&imageurl=https://nova.astrometry.net/image/11018065&credits=Astrometry.net+User+(All+Rights+Reserved)&creditsUrl=&ra=87.272483&dec=-9.748588&x=580.4&y=2233.9&rotation=-93.05&thumb=https://nova.astrometry.net/image/11018069&wtml=true

)

Tracing through the rendering, I see that `renderPart` for this image is now using the WebGL2 FITS path, while it should be using some plain-vanilla image texture rendering.

Do you have a chance to take a look at this?

**Comment by imbasimba** [comment]
Yes! I noticed an error in the code yesterday that I suspected would break the regular images. I did fix it in my tiled-fits branch, which I estimate to open a PR for very soon. But just in case that branch will take longer than expected, I'll open a separate PR just containing the fix

**Comment by imbasimba** [comment]
https://github.com/WorldWideTelescope/wwt-webgl-engine/pull/114

**Comment by pkgw** [comment]
Excellent, very much appreciated! This functionality is exposed from Astrometry.Net's WWT linkage, and I've gotten two emails asking about it, which implies that it's quite highly used ...

**Comment by pkgw** [comment]
I released the fix and this seems to be working again.
