### ISSUE TITLE
Longitudes of planetary layers

### ISSUE THREAD

**Issue by Carifio24** [WorldWideTelescope/wwt-webgl-engine#177]
While investigating some speed issues with `glue-wwt`, I came across what looks like the next chapter of the 180-degree longitude flipping saga. The issue is that a layer on the Earth had some points that were flipped by 180 degrees - what was supposed to be airline data over Boston was showing up over northern China. I initially chalked this up to the previous 180 degree issue (since the corresponding glue-wwt changes haven't shown up in a release yet), but that only affects 3D layers. Thus, I think there's still a problem with planetary layers, which have both `astronomical` and `bufferIsFlat` false. I'll look into how best to deal with this.

To see this in action, download the attached `planes_truncated.csv` file (which contains part of the data from the layer described above) and run the following in a Jupyter notebook in an environment with the newest version of `pywwt` (which uses the newest research app release).

```
from pywwt.jupyter import WWTJupyterWidget
from astropy.io import ascii

wwt = WWTJupyterWidget()
frame = 'Earth'
table = ascii.read('planes_truncated.csv')
wwt.layers.add_table_layer(table, frame=frame)
wwt._send_msg(event="set_background_by_name", name=frame)
wwt
```

[planes_truncated.csv](https://github.com/WorldWideTelescope/wwt-webgl-engine/files/8248282/planes_truncated.csv)

**Comment by Carifio24** [comment]
So I decided to do some investigation of the `bufferIsFlat` and `astronomical` parameters. It would be nice to have this saved somewhere better (and in a better-written form), but for the purposes of this issue, I'll put what I've found here.

# bufferIsFlat

* Set in one place:
    - In Draw, SpreadSheetLayer.cs 2622
        * Set to `flat`

    - Draw is called in `LayerManager::Draw`, at line 940
    - In both cases the argument for `flat` is `cosmos`

        * `LayerManager::Draw` is called at 4 places:
            - Recursive call with same value at line 1003
            - Called with cosmos = false in `Planets::DrawPlanet3d` (line 1857)
            - Called with cosmos = false in `WWTControl::RenderOneFrame` (line 576), only when in solar system mode
            - Called with cosmos = `Space` in `WWTControl::RenderOneFrame` (line 710), if either `PlanetLike` or `Space` is true
                * `Space` is true if we're in sky mode, or the background imageset is null
                * `PlanetLike` is true if we're in Earth or Planet mode

# astronomical/Astronomical

* Set to true when creating a `SpreadSheetLayer` from a `VoTable` if the table has either an RA or Dec column (`SpreadSheetLayer::GuessHeaderAssignmentFromVoTable`)
* Set to true when guessing header assignments if either an RA or Dec column is found (`SpreadSheetLayer::GuessHeaderAssignment`)
* Set to true in `LayerManager::PreDraw` (line 1153) if the layer is in the Sky reference frame
* Set to `astronomical` in `LayerManager::Draw` (line 935)
    - `LayerManager::Draw` is called in 4 places, as above:
        * Recursive call with same value at line 1003
        * Called with astronomical = false in `Planets::DrawPlanet3d` (line 1857)
        * Called with astronomical = true in `WWTControl::RenderOneFrame` (line 576), only when in solar system mode
        * Called with astronomical = `Space` in `WWTControl::RenderOneFrame` (line 710), if either `PlanetLike` or `Space` is true


Based on this, it looks like `astronomical` is false for planetary layers and true otherwise, while `bufferIsFlat` is only true if we're in sky mode. Thus, for the various modes, I think this gives us

SolarSystem: `astronomical = true`, `bufferIsFlat = false`
Earth/Planet: `astronomical = bufferIsFlat = false`
Sky: `astronomical = bufferIsFlat = true`
Panorama: `astronomical = bufferIsFlat = false`

**Comment by astrojonathan** [comment]
I am to blame for this travesty. WWT started out with just Sky mode, when we added the solar system mode we had to adapt the display engine to handle drawing in 3d space transformed into sun-centered coordinates, or on any given planet or coordinate frame, sometimes deeply nested. The sky code had an inverted Z compared to the solar system mode and the way 3d coordinates were calculated and rendered was different, so we had to have a way of shoehorning them all together. If I had to start from scratch we would not have had such kludges, but keeping backward compatibility with millions of installed users back then without breaking tours, layers, etc. was a priority.

**Comment by Carifio24** [comment]
Yeah, I'm not surprised at all that adding extra modes as the application grew lead to kludgy stuff. I don't think that this particular issue used to be present, so I'm suspicious that this may be an unintended consequence of #166, and that that PR traded one problem for another.
