### ISSUE TITLE
Research app point selection can break on Firefox

### ISSUE THREAD

**Issue by Carifio24** [WorldWideTelescope/wwt-webgl-engine#216]
First noticed by @pkgw. Selection of catalog sources in the research app breaks on Firefox as soon as one has clicked the mouse inside of the WWT component (that is, not on any of the UI elements). The cursor will stay in whatever state it was when first clicked.

Some preliminary investigation showed the cause of the problem - after the mouse has been pressed down on Firefox, the app component no longer receives any pointer events (monitoring events on the document with the function [described here](https://stackoverflow.com/questions/50666956/whats-the-monitorevents-equivalent-for-firefox), there don't seem to be any pointermove events emitted). Firefox does, however, still get mousemove events after a click (Chrome continues to get both, which is why things work fine).

I tried this out on Vivaldi and Safari, and neither have this issue - seems to be a Firefox thing. I looked at the events around the click action, since that's what breaks things on FF, using `monitorEvents` in Chrome and the above-linked function in Firefox. What I got is:

Chrome:
pointerdown -> mousedown -> gotpointercapture -> pointerup -> mouseup -> lostpointercapture

Firefox:
pointerdown -> mousedown -> focus -> gotpointercapture -> pointerup -> lostpointercapture -> mouseup -> click

The order of events is slightly different, but I'm not sure what in there would leave to different behavior.

**Comment by Carifio24** [comment]
That's a good thought, but the point selection implementation doesn't use any references to pointerId (at least right now, it doesn't care where the movement/press comes from).

I think I've made another step towards figuring this out, though. When I used `monitorEvents` the other day, I was looking at the `document`, and was seeing that only Chrome was showing `pointermove` events after a click. However, monitoring the events on the WebGL canvas shows that the canvas gets `pointermove` events after a click in both browsers. However, the events in Chrome have `defaultPrevented: false`, while those in Firefox have `defaultPrevented: true`. Basically, after a click, the events in Firefox aren't bubbling up to the app component.

**Comment by Carifio24** [comment]
We actually call `preventDefault()` and `stopPropagation()` in the canvas's `pointermove` event listener [here](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/WWTControl.cs#L1505). After building the engine with these lines commented out, the point selection works fine in Firefox (and still seems fine in Chrome). So maybe this issue is because Firefox is the only one doing what we tell it to?

**Comment by Carifio24** [comment]
At least in my experimentation, it doesn't seem like the `pointerId` is getting changed in Firefox. Unless I'm mistaken, isn't the block at the top of that function checking whether the pointer IDs for two fingers (or styluses, etc) have been swapped by the browser during a touchscreen pinch-zoom?

Going off what you said about the user click-dragging, there is a `mouseDown` member value that I think we could use - instead of always doing preventDefault/stopPropagation, we could only call them if the mouse is down:

```
if (mouseDown)
{
    e.StopPropagation();
    e.PreventDefault();
}
```

It seems like even that might still cause problems for the intended use cases of https://github.com/WorldWideTelescope/wwt-webgl-engine/pull/205 though - if the message never reaches the research app, the `wwt_pointer_move` message (which only fires when a button is pressed anyways) won't be sent.

**Comment by pkgw** [comment]
If I'm remembering correctly, the `else { return; }` bit is part of an intent for the function to do nothing and exit if no button is down — pointerIds should only be non-zero between the `pointerdown` and `pointerup` events (and I think it's guaranteed that the pointer IDs will never be 0).

But that being said, the use case in #205 is another thing to keep in mind. I *think* that might be covering a slightly different set of circumstances, since I think the issue there was when the click was initiated outside of WWT, rather than inside of WWT as here. But also, if there aren't any obvious problems stemming from *not* stopPropagation/preventDefault on the drag events, we should probably just take yes for an answer and remove those lines.

**Comment by Carifio24** [comment]
>  (and I think it's guaranteed that the pointer IDs will never be 0).

I think that's it! That would've seemed like a reasonable condition to me, but turns out not to be true. Chrome (and Vivaldi) report the pointerId of the mouse as 1, but Firefox is always reporting it as 0 for me. Our pointerId values both start as undefined (in the transpiled JS - they would be 0 in the C#), but we explicitly set the relevant pointerId to 0 on a pointerup [here](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/WWTControl.cs#L1516) - this is why it takes a click to break things on Firefox.

MDN just says that pointerId is a number, which means there isn't an obviously dummy value we can use on the C# side (unless we do some boxing/unboxing and use `null`). [W3 says](https://www.w3.org/TR/pointerevents3/#pointerevent-interface) "The pointerId value of -1 MUST be reserved and used to indicate events that were generated by something other than a pointing device." I don't know exactly what that means, or what the consequences of overlapping with that reserved value could be.
