### ISSUE TITLE
Showing telescope FOV using JS API

### ISSUE THREAD

**Issue by SteveWTS** [WorldWideTelescope/wwt-webgl-engine#245]
I’m experimenting with the embedded hosted version ([WWT WebGL Engine Reference Manual](https://docs.worldwidetelescope.org/webgl-reference/latest/getting-started/hosted-javascript-model/)).

I’m trying to restrict the camera zoom / FOV or draw an overlay showing FOV, to simulate the view of a telescope / camera combination. Similar to this function: [Showing fields of view — pywwt 0.15.2 documentation](https://pywwt.readthedocs.io/en/stable/fov.html)

Is this possible with the embedded version?

**Comment by pkgw** [comment]
@swaterfall Most definitely! The basic interface you want is some variation of [`gotoRADecZoom`][1]. The most surprising thing is that the zoom level is defined somewhat oddly: it is the angular height of the viewport, measured in degrees, times six. So if you want the viewport to be 1 degree tall, you set the zoom parameter to 6. If you have a rectangular region of interest, for the best results you have to take into account the aspect ratios of both that region and the viewport to figure out the appropriate zoom setting.

[1]: https://docs.worldwidetelescope.org/webgl-reference/latest/apiref/engine/classes/WWTControl-1.html#gotoRADecZoom

**Comment by pkgw** [comment]
Great! I'll go ahead and close this issue, then, but feel free to follow up as needed. Also if whatever you're working on ends up being publicly available, please send me/us a link!
