### ISSUE TITLE
(Hosted Javascript Model) LoadImageCollection: not working to load new image collection from URL

### ISSUE THREAD

**Issue by NeyasG** [WorldWideTelescope/wwt-webgl-engine#252]
# (Hosted Javascript Model) LoadImageCollection: not working to load new image collection from URL.

I can't seem to load a new imageset while running the code below. Despite having no errors the length of the available imagesets list is the same after `loadImageCollection` is called. 

I was using the Firefox debugger to set breakpoints and test whether the imageset was being loaded at all and confirmed that the URL was valid and the file was downloaded and parsed but it doesn't appear in the singleton object and the available imagesets remained the default length.

```javascript
// create function to initialise wwt and fire ready event
function init_wwt() {
    wwt = wwtlib.WWTControl.initControl('wwtcanvas');
        wwt.add_ready(wwtReady);
}

// Function to setup the initial default settings of the engine
function wwtReady(wwt) {
    
    // Check imageset list length
    console.log((wwtlib.WWTControl.getImageSets().length))
    // 88

    wwt.loadImageCollection("https://data1.wwtassets.org/packages/2022/08_jwst/ceers_nircam/index.wtml", true)
    wwt.loadImageCollection("http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=hips", true)

    // Check imageset list length
    console.log((wwtlib.WWTControl.getImageSets().length))
    // 88

    // wwt.singleton.setBackgroundImageByName("EGRET")
    wwtlib.WWTControl.singleton.setBackgroundImageByName("EGRET")
}

// Calls init_wwt when HTML DOM is loaded
window.addEventListener('load', init_wwt);
```

**Comment by Carifio24** [comment]
Hi @NeyasG, image collection loading is asynchronous (as the data needs to be loaded from the given URL), so it takes some time for the collection of imagesets to update. In this example, the second `console.log` is running before either collection has finished loading. If you want to do something when a collection is loaded, you can listen for the `collectionLoaded` event ([relevant docs here](https://docs.worldwidetelescope.org/webgl-reference/latest/apiref/engine/classes/scriptinterface.html#loadimagecollection)). This example re-logs the count after each collection finishes loading:
```
function wwtReady(wwt) {
    
    // Check imageset list length
    console.log((wwtlib.WWTControl.getImageSets().length))
    // 88

    wwt.add_collectionLoaded(() => {
      console.log(wwtlib.WWTControl.getImageSets().length);
    });

    wwt.loadImageCollection("https://data1.wwtassets.org/packages/2022/08_jwst/ceers_nircam/index.wtml", true)
    wwt.loadImageCollection("http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=hips", true)

    // wwt.singleton.setBackgroundImageByName("EGRET")
    wwtlib.WWTControl.singleton.setBackgroundImageByName("EGRET")
}
```

**Comment by pkgw** [comment]
Thanks for the quick follow-up @Carifio24 ! @NeyasG, I'll just mention that you may find that your life becomes a lot easier if you're able to use async/await constructs in your JavaScript code, because WWT has a lot of these sort of asynchronous operations.

**Comment by NeyasG** [comment]
@Carifio24 Ah I see thanks for the quick reply. I'm very new to this so I appreciate your explanation! 

@pkgw I'll put that on the list of things I need to learn, thanks for the advice!
