### ISSUE TITLE
Possible issue with tracking objects in local horizon mode

### ISSUE THREAD

**Issue by Carifio24** [WorldWideTelescope/wwt-webgl-engine#268]
I'm trying to make a sky mode view that follows the Sun while using local horizon mode. I've got the Sun set as the tracking object, but it seems that the tracking only works when I turn local horizon mode off.

After digging around in the code, I _think_ that the issue is that, in local horizon mode, the actual Alt/Az values for the render context aren't updated (only the target values are). It seems like the two assignments [here](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/WWTControl.cs#L1075) should look more like the ones in the preceding block [here](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/WWTControl.cs#L1068). With this change, my local-horizon-mode view does indeed stay centered on the Sun as time passes.

@pkgw does this make sense to you? Or is there something that I'm missing here?

**Comment by pkgw** [comment]
New code references, after the ESM/JS port:

- [Local horizon mode assignment](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/esm/wwt_control.js#L978-L979)
- [Galactic mode assignment](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/esm/wwt_control.js#L973-L974)

I agree that it seems like the local horizon mode should do the same thing as the galactic mode ... and/or, I see no reason why it shouldn't! I wouldn't be surprised if an oversight was discovered in the galactic mode, but the fix wasn't propagated to local horizon mode.

**Comment by Carifio24** [comment]
> I wouldn't be surprised if an oversight was discovered in the galactic mode, but the fix wasn't propagated to local horizon mode.

Yeah, I agree that's the most likely reason for the discrepancy. Since the JS port has been merged, I can open a PR to make the suggested change.
