### ISSUE TITLE
Io/Europa/Ganymede/Calisto orbits not visible

### ISSUE THREAD

**Issue by srcejon** [WorldWideTelescope/wwt-webgl-engine#296]
In the Solar System view, it seems the orbits of Io/Europa/Ganymede/Calisto aren't displayed, even if "Planetary Orbits" and "Moon & Satellite Orbits" are both checked.

In the Windows client, orbits for these moons are displayed when only "Planetary orbits" is checked.

![image](https://github.com/WorldWideTelescope/wwt-webgl-engine/assets/57259258/5a8aaa28-d552-43a7-b6bb-e999bdf0ef18)

**Comment by pkgw** [comment]
As far as I can tell, it turns out that there was some custom code in the Windows client to draw these orbits, and it simply never made its way into the WebGL engine. #298 should fix this.
