### ISSUE TITLE
Chrome haywire mouse behavior

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-webgl-engine#58]
A couple users reported this, and @heywooddogwood and I have been able to reproduce it multiple times in Chrome.  We haven't been able to make this happen in Safari or Firefox:

- Open WWT web client in Chrome
- Pan around the sky, zoom in and out
- Click on various image thumbnails (we're not sure if this is critical to triggering the weird behavior)
- Eventually, the mouse will go out of control. Any attempt to click and pan instead sends the view into a super zoomed mode, seen just after 9 seconds in [this](https://drive.google.com/file/d/1hSCmHHMUmpnqKoQ_CcoXHvwpdXzsdDqD/view?usp=sharing) screen capture I made.
- The only way we've been able to find to fix it is to reload WWT, but then it will eventually happen again in Chrome.

**Comment by pkgw** [comment]
After obtaining more detailed logs, it seems that the culprit is that Chrome/Mac is sometimes failing to deliver pointerUp events.
